#!/usr/bin/env node
// tools/make-page.mjs — the fixpoint. index.html runs the SAME tier.mjs, prices.mjs and stack.mjs the tests and the
// mutation gate prove, over the committed registry, organ map, GitHub evidence and example stack. Each module runs
// in its own scope so helper names cannot clash. CI regenerates the page and fails if it differs.
import { readFileSync, writeFileSync } from 'node:fs';
const at = (f) => new URL('../' + f, import.meta.url);
const read = (f) => readFileSync(at(f), 'utf8').replace(/\r\n/g, '\n');
const json = (f) => JSON.parse(read(f));
const strip = (src) => src.split('\n').filter((l) => !/^import .* from '\.\/[a-z]+\.mjs';$/.test(l) && !/^export default /.test(l)).join('\n').replace(/^export /gm, '').trimEnd();
const scoped = (f, names) => '// ── ' + f + ' (own scope) ──\nconst { ' + names.join(', ') + ' } = (() => {\n' + strip(read(f)) + '\nreturn { ' + names.join(', ') + ' };\n})();';
const kernel = [
  scoped('tier.mjs', ['tierOf']),
  scoped('prices.mjs', ['KINDS', 'days', 'checkRegistry', 'lookup', 'exVat', 'toGbp']),
  scoped('stack.mjs', ['audit', 'replacement']),
].join('\n\n');
const stack = json('data/bank-stack.json');
const data = { registry: json('registry/prices.json'), organs: json('registry/organs.json'), evidence: json('registry/tier-evidence.json').organs, stack: stack.stack };
let page = read('index.html');
const swap = (begin, end, body) => {
  const a = page.indexOf(begin), z = page.indexOf(end);
  if (a < 0 || z < a) { console.error('markers missing: ' + begin); process.exit(1); }
  page = page.slice(0, a + begin.length) + '\n' + body + '\n' + page.slice(z);
};
swap('<!-- ⟦DATA-BEGIN⟧ generated by tools/make-page.mjs — do not edit here -->', '<!-- ⟦DATA-END⟧ -->', '<script type="application/json" id="stackData">' + JSON.stringify(data).replace(/</g, '\u003c') + '</script>');
swap('// ⟦KERNEL-BEGIN⟧ generated from tier.mjs, prices.mjs and stack.mjs by tools/make-page.mjs — do not edit here', '// ⟦KERNEL-END⟧', kernel);
writeFileSync(at('index.html'), page);
console.log('page: kernel ' + kernel.length + ' chars · data ' + JSON.stringify(data).length + ' chars · ' + data.registry.entries.length + ' registry entries');
